### ISSUE TITLE
What is "torch_scorer_vars.bin"?

### ISSUE THREAD

**Issue by jo-kyeongbin** [pitrack/incremental-coref#1]
torch_scores.py (line : 197)

I found "torch_scorer_vars.bin". It is different with bert_base model's keys.
thus, genre_embedder, span_scorer and scoring_module raise key errors.

help this problem. thanks!

**Comment by pitrack** [comment]
Where are you getting "torch_scorer_vars.bin" from? Is it from the output of this script https://github.com/pitrack/incremental-coref/blob/emnlp2020/conversion_scripts/convert_tf_to_pt.sh?

This script takes in a tf bert checkpoint that's download from this repo: https://github.com/mandarjoshi90/coref

**Comment by jo-kyeongbin** [comment]
Thank you for quick response. It was really helpful, thank you.
